"""v2_models

Revision ID: 3eb3de3b6d24
Revises: ab6beb81ed4f
Create Date: 2026-02-07 19:30:06.535371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""v2_models

Revision ID: 3eb3de3b6d24
Revises: ab6beb81ed4f
Create Date: 2026-02-07 19:30:06.535371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb3de3b6d24'
down_revision = 'ab6beb81ed4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Handle Enums safely
    conn = op.get_bind()
    ticket_priority = sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority')
    ticket_type = sa.Enum('BUG', 'TASK', 'FEATURE', name='tickettype')
    
    # Check if they exist before creating
    # Using raw SQL for safety in PG
    conn.execute(sa.text("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ticketpriority') THEN CREATE TYPE ticketpriority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'); END IF; END $$;"))
    conn.execute(sa.text("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tickettype') THEN CREATE TYPE tickettype AS ENUM ('BUG', 'TASK', 'FEATURE'); END IF; END $$;"))

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.add_column('tickets', sa.Column('priority', ticket_priority, nullable=True))
    op.add_column('tickets', sa.Column('ticket_type', ticket_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'ticket_type')
    op.drop_column('tickets', 'priority')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
