"""add workspace membership

Revision ID: ab6beb81ed4f
Revises: 6c6f971c8b4b
Create Date: 2026-02-03 17:46:22.175555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6beb81ed4f'
down_revision = '6c6f971c8b4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_members', sa.Column('joined_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('workspace_members_user_id_fkey'), 'workspace_members', type_='foreignkey')
    op.drop_constraint(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'workspace_members', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('workspace_members_user_id_fkey'), 'workspace_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workspace_members', 'joined_at')
    # ### end Alembic commands ###
