"""add owner_id to workspace

Revision ID: c40e3a4090ba
Revises: 1a2b3c4d5e6f
Create Date: 2026-02-03 17:22:16.437514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add owner_id to workspace

Revision ID: c40e3a4090ba
Revises: 1a2b3c4d5e6f
Create Date: 2026-02-03 17:22:16.437514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40e3a4090ba'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('workspaces', sa.Column('owner_id', sa.Integer(), nullable=True))
    
    # Try to assign existing workspaces to the first user found (if any)
    # This is a bit of a hack for dev, but it avoids the "NOT NULL" crash
    op.execute("UPDATE workspaces SET owner_id = (SELECT id FROM users LIMIT 1) WHERE owner_id IS NULL")
    
    # If there ARE workspaces but NO users, the above won't help and it will still fail.
    # So we'll only make it NOT NULL after assigning.
    op.alter_column('workspaces', 'owner_id', nullable=False)
    
    op.create_foreign_key(None, 'workspaces', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'owner_id')
    # ### end Alembic commands ###
